output_dir: "cam3zju_zjuval/"
device: "cuda"
dist_backend: "nccl"
log_dir: "logs/"
result_dir: "results/"
seed: 42
workers: 4
pi: "psnr"
cam_num: 3
fix_human: False
fix_pose: False
mask_bkgd: True
src_view_num: 3
dataset:
  img_num_per_gpu: 1
  H: 1024
  W: 1024
  ratio: 0.5
  voxel_size: [0.005, 0.005, 0.005]
  train:
    name: "zju_mocap"
    file: "ZjumocapDataset"
    data_root: "data/zju_mocap"
    seq_list: ['CoreView_313', 'CoreView_377', 'CoreView_394', 'CoreView_315', 'CoreView_386', 'CoreView_390']
    dataset_cams: 24
    drop_last: True
    shuffle: True
    chunk: 400
  test:
    name: "zju_mocap"
    file: "ZjumocapDataset"
    data_root: "data/zju_mocap"
    dataset_cams: 24
    drop_last: False
    shuffle: True
    sampler: ""
    seq_list: ['CoreView_387', 'CoreView_393', 'CoreView_392']
    interval: 6 #1
    chunk: 2000
render:
  file: "BaseRender"
  # resume_path: "/code/DigitalHumanNeRF/code/code/356.pth"
encoder:
  name: "resnet34" # ['resnet18', 'resnet34', 'resnet50', 'resnet101', 'resnet152']
  file: "UNet"
  out_ch: 32
head:
  file: "trainhead"
  rgb:
    use_rgbhead: True # ban rgbhead when test mesh
  sigma:
    code_dim: 32
    n_heads: 4
    n_layers: 4
    n_smpl: 6890
    outdims: [32, 32, 32, 32]
train:
  file: "BaseTrainer"
  criterion_file: "BaseNeRFCriterion"
  resume: True
  body_sample_ratio: 0.5
  n_rays: 1024
  n_samples: 64
  lr: 1e-4
  gamma: 0.1 #exponentiallr scheduler
  decay_epochs: 1000 #exponentiallr scheduler
  weight_decay: 0.0001 #adamW
  max_epoch: 1000
  print_freq: 10
  save_every_checkpoint: True
  save_interval: 1
  valiter_interval: 100
  val_when_train: True
test:
  save_imgs: True
  test_seq: "CoreView_315"
  is_vis: True
  mesh_th: 50
